Server: Add client connection timeout
shakram02/tftpeer pull request #2
Opened 2020-10-07 22:35 UTC by Abogical

Fixes #1

2020-10-08 07:11 UTC, shakram02 commented on src/tftp/server.rs
> +    socket.set_read_timeout(Some(Duration::from_secs(5)));
Can we move this to a constant?

2020-10-08 07:13 UTC, shakram02 requested changes

2020-10-08 07:13 UTC, shakram02 commented on src/tftp/server.rs
>      // });
please remove this also, I forgot to remove it

2020-10-08 11:19 UTC, Abogical commented
Done!

2020-10-09 12:31 UTC, shakram02 commented on src/tftp/server.rs
> +    const sock_dur: Option<Duration> = Some(Duration::from_secs(5));
`sock_dur` isn't a function constant (as it's a program property), so it's best placed at the top of the file

2020-10-09 12:32 UTC, shakram02 approved these changes

2020-10-10 09:12 UTC, merged